### ISSUE TITLE
 Error: TypeError("search_people()

### ISSUE THREAD

**Issue by GitHackerDoBem** [bigoulours/linkedin-search-export-to-excel#1]
Error: TypeError("search_people() got an unexpected keyword argument 'keyword_title'") in linkedInSearch.py line 86

**Comment by bigoulours** [comment]
Hi!
thanks for looking into my project!
Have you installed the correct version of linkedin-api?
Like I stated in the README.md you should install it with:
```
pip install linkedin-api~=2.0.0a
```
Per default pip will install an older one

EDIT: I added a requirements.txt. anyone should be able to run the program after running:
```
pip install -r requirements.txt
```
